version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/application
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: DB_base
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: word
    volumes:
      - .dbdata:/var/lib/mysql
